400: org.ginsim.core.graph.GraphManager.open()::  Exception is :
org.ginsim.common.application.GsException: Parsing error : Premature end of file.:
Exception is : Premature end of file.
	at org.ginsim.common.xml.XMLHelper.startParsing(XMLHelper.java:214)
	at org.ginsim.core.graph.regulatorygraph.perturbation.PerturbationManager.doOpen(PerturbationManager.java:31)
	at org.ginsim.core.graph.regulatorygraph.perturbation.PerturbationManager.doOpen(PerturbationManager.java:19)
	at org.ginsim.core.graph.GraphManager.open(GraphManager.java:397)
	at org.ginsim.core.graph.GraphManager.open(GraphManager.java:337)
	at org.ginsim.ScriptLauncher.open(ScriptLauncher.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:404)
	at org.python.core.PyObject.__call__(PyObject.java:408)
	at org.python.core.PyMethod.__call__(PyMethod.java:124)
	at org.python.pycode._pyx0.f$0(./scripts/ginsim/FindStableState.py:117)
	at org.python.pycode._pyx0.call_function(./scripts/ginsim/FindStableState.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:165)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1275)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:522)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:225)
	at org.ginsim.ScriptLauncher.run(ScriptLauncher.java:133)
	at org.ginsim.Launcher.main(Launcher.java:79)
